# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  authy_key: XDeXBF06jcj7qpjJTlSKMPZQIOnN9s5j
  secret_key_base: ebda9fcb07a0f9bbafc3728820b5bcdb7b49f9a0b42fb5e6f1ae6f8f353d274a7523788577ff9d99a0347894cd878956d6dd353fa96127f361ac6b23be1689ef

test:
  secret_key_base: 1a173bfdcf685278bf8e1e955ef4c3a0f81bf000a2e943dd19940ac1260b2dd62937ffa322812d9396479fe54e6cc411575dae338d6607431afc52e75e9b189b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
